### ISSUE TITLE
Fix redirects for whole solution

### ISSUE THREAD

**Issue by fantastory** [CloudNimble/BindingRedirectsDoctor#1]
### Installed product versions
- Visual Studio: 2017 Comunity
- This extension: 1.0.1

### Description
Let there be an option to fix all binding redirections for whole solution with one click.

**Comment by robertmclaws** [comment]
Hello! Thanks for opening up this issue, and really appreciate the feedback. I would be hesitant to try to do this to every project, might have unexpected results. I think we're going to leave it the way it is for now, but we'll keep it in mind in the future.

BTW, we finally updated it for VS2019, so if you've upgraded, check it out! :)
