### ISSUE TITLE
CreateInstance failed for package  [FixRedirectsCommandPackage]Source: 'mscorlib' Description: Could not load file  or assembly 'Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0,  

### ISSUE THREAD

**Issue by febitanya** [CloudNimble/BindingRedirectsDoctor#5]
### Installed product versions
- Visual Studio: 2017 ent
- This extension: 1.1.4

# | Type | Description | GUID | Hr | Source | Time (UTC)
1448 | ERROR | CreateInstance failed for package  [FixRedirectsCommandPackage]Source: 'mscorlib' Description: Could not load file  or assembly 'Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0,  Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.  The system cannot find the file specified. System.IO.FileNotFoundException:  Could not load file or assembly 'Microsoft.VisualStudio.Shell.15.0,  Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of  its dependencies. The system cannot find the file specified. File name:  'Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral,  PublicKeyToken=b03f5f7f11d50a3a' at  System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name,  Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type) at  System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError,  Boolean ignoreCase) at System.Activator.CreateInstanceFromInternal(String  assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr,  Binder binder, Object[] args, CultureInfo culture, Object[]  activationAttributes, Evidence securityInfo) at  System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName) WRN:  Assembly binding logging is turned OFF. To enable assembly bind failure logging,  set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.  Note: There is some performance penalty associated with assembly bind failure  logging. To turn this feature off, remove the registry value  [HKLM\Software\Microsoft\Fusion!EnableLog]. | {402B69C6-E132-417A-A347-22BEA9368042} | 80004005 - E_FAIL | VisualStudio | 2019/09/27 18:57:37.515

**Comment by robertmclaws** [comment]
Hello! We released a new version of the add-in that updates how it loads those assemblies, and adds VS2019 support. Please try it again and see if it works for you. Feel free to re-open if you have any issues. Thanks!
