### ISSUE TITLE
Not working with Vs 2019

### ISSUE THREAD

**Issue by JAspeling** [CloudNimble/BindingRedirectsDoctor#6]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 1.0.1

### Description
It fails to install when I only have vs 2019 installed

### Expected behavior
To be compatible with Visual Studio 2019

**Comment by robertmclaws** [comment]
Thanks for pointing this out! The latest build works with VS2019. Try searching for it from the Extensions method, you should see it now!

Thanks!
